name = "yy8-blog"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./"

# Cloudflare Pages Functions
# [[d1_databases]]
# binding = "DB"
# database_name = "blog_db"
# database_id = "7f5ce7b6-0ffa-467e-9ff6-87afafff0ead"